#!/usr/bin/ruby
# A rjr integration stress test client
#
# Copyright (C) 2013 Mohammed Morsi <mo@morsi.org>
# Licensed under the Apache License, Version 2.0

require 'rjr/nodes/amqp'

client_id = ARGV[0]

#RJR::Logger.log_level = ::Logger::DEBUG

amqp_node  = RJR::Nodes::AMQP.new :node_id => "stress_test_client#{client_id}", :broker => 'localhost'
amqp_node.listen

amqp_node.dispatcher.handle("client_callback") { |p|
  puts "invoked #{client_id} client_callback method #{p}"
  #amqp_node.invoke_request('stress_test-queue', 'stress', "foozmoney#{client_id}")
  #amqp_node.halt
  nil
}

res = amqp_node.notify('stress_test-queue', 'stress', "foobar#{client_id}")
res = amqp_node.invoke('stress_test-queue', 'stress_callback', "#{client_id}")
puts "Result #{amqp_node.node_id} #{res}"

#amqp_node.join
