#!/usr/bin/ruby
# A rjr integration stress test long-running client
#
# Copyright (C) 2013 Mohammed Morsi <mo@morsi.org>
# Licensed under the Apache License, Version 2.0


require 'rjr/nodes/amqp'

client_id = ARGV[0]

#RJR::Logger.log_level = ::Logger::DEBUG

amqp_node  = RJR::Nodes::AMQP.new :node_id => "stress_test_long_client#{client_id}", :broker => 'localhost',
                               :keep_alive => true

0.upto(100) { |i|
  res = amqp_node.notify('stress_test-queue', 'stress', "foobar#{client_id}")
  puts "Result #{amqp_node.node_id} #{res}"
}
