#!/usr/bin/ruby
# A rjr integration stress test client

require 'rubygems'
require 'rjr'

client_id = ARGV[0]

#RJR::Logger.log_level = ::Logger::DEBUG

amqp_node  = RJR::AMQPNode.new :node_id => "stress_test_client#{client_id}", :broker => 'localhost'
amqp_node.listen

RJR::Dispatcher.add_handler("client_callback") { |p|
  puts "invoked #{client_id} client_callback method #{p}"
  #amqp_node.invoke_request('stress_test-queue', 'stress', "foozmoney#{client_id}")
  amqp_node.stop
  nil
}

res = amqp_node.invoke_request('stress_test-queue', 'stress', "foobar#{client_id}")
res = amqp_node.invoke_request('stress_test-queue', 'stress_callback', "#{client_id}")
puts "Result #{amqp_node.node_id} #{res}"

amqp_node.join
