#!/usr/bin/ruby
# A rjr integration stress test long-running client

require 'rubygems'
require 'rjr'

client_id = ARGV[0]

#RJR::Logger.log_level = ::Logger::DEBUG

amqp_node  = RJR::AMQPNode.new :node_id => "stress_test_long_client#{client_id}", :broker => 'localhost',
                               :keep_alive => true

0.upto(100) { |i|
  res = amqp_node.invoke_request('stress_test-queue', 'stress', "foobar#{client_id}")
  puts "Result #{amqp_node.node_id} #{res}"
}
