#!/usr/bin/ruby
# runs the integration test

cd = File.expand_path(File.dirname(__FILE__))

server_thread = Thread.new { 
  puts "Starting server"
  system("#{cd}/server")
  puts "Server finished"
}
sleep 2

finished = 0
client_threads = []
thread_map = {}
0.upto(500) { |i|
  client_threads <<
    Thread.new {
      puts "Starting client #{i}"
      system("#{cd}/client #{i}")
      puts "Client #{i} finished (#{finished+=1})"
    }
  thread_map[client_threads.last] = i
}

client_threads.each { |th| th.join }
