#!/usr/bin/ruby
# runs the stress example
#
# Copyright (C) 2013 Mohammed Morsi <mo@morsi.org>
# Licensed under the Apache License, Version 2.0

cd = File.expand_path(File.dirname(__FILE__))

server_pid = nil
server_thread = Thread.new { 
  puts "Starting server"
  system("#{cd}/server")
  puts "Server finished"
}
sleep 2

finished = 0
client_threads = []
thread_map = {}
0.upto(250) { |i|
  client_threads <<
    Thread.new {
      puts "Starting client #{i}"
      system("#{cd}/client #{i}")
      puts "Client #{i} finished (#{finished+=1})"
    }
  thread_map[client_threads.last] = i

  client_threads <<
    Thread.new {
      puts "Starting long running client #{i}"
      system("#{cd}/long-client #{i}")
      puts "Long Client #{i} finished (#{finished+=1})"
    }
}

client_threads.each { |th| th.join }
